
const Q=window.QUESTION_BANK||[]; const LS='taipowerQuizV1'; let state=JSON.parse(localStorage.getItem(LS)||'{"answers":{},"favorite":{}}'); let list=[],idx=0,selected=null,shown=false;
const $=s=>document.querySelector(s); const save=()=>localStorage.setItem(LS,JSON.stringify(state));
function init(){[...new Set(Q.map(q=>q.year))].sort().forEach(y=>$('#year').add(new Option(y+' 年',y)));[...new Set(Q.map(q=>q.topic))].sort().forEach(t=>$('#topic').add(new Option(t,t))); ['year','topic','status'].forEach(id=>$('#'+id).onchange=filter); $('#search').oninput=filter; $('#random').onclick=()=>{if(list.length){idx=Math.floor(Math.random()*list.length);selected=null;shown=false;render()}};$('#reset').onclick=()=>{if(confirm('確定清除所有作答、錯題與收藏紀錄？')){state={answers:{},favorite:{}};save();filter()}};filter();renderPapers()}
function filter(){let y=$('#year').value,t=$('#topic').value,s=$('#status').value,k=$('#search').value.trim().toLowerCase();list=Q.filter(q=>(y==='all'||String(q.year)===y)&&(t==='all'||q.topic===t)&&(!k||q.text.toLowerCase().includes(k)||q.topic.toLowerCase().includes(k)));if(s!=='all')list=list.filter(q=>{let a=state.answers[q.id],f=state.favorite[q.id];if(s==='unanswered')return !a;if(s==='answered')return !!a;if(s==='wrong')return a&&q.answer&&a.choice!==q.answer;if(s==='favorite')return !!f});idx=0;selected=null;shown=false;render();stats()}
function stats(){let done=list.filter(q=>state.answers[q.id]).length, graded=list.filter(q=>state.answers[q.id]&&q.answer),ok=graded.filter(q=>state.answers[q.id].choice===q.answer).length;$('#sTotal').textContent=list.length;$('#sDone').textContent=done;$('#sRate').textContent=graded.length?Math.round(ok/graded.length*100)+'%':'—';$('#sFav').textContent=list.filter(q=>state.favorite[q.id]|| (state.answers[q.id]&&q.answer&&state.answers[q.id].choice!==q.answer)).length}
function render(){let box=$('#quiz');if(!list.length){box.innerHTML='<div class="card empty">沒有符合目前篩選條件的題目。</div>';stats();return}let q=list[idx];let old=state.answers[q.id];selected=selected||old?.choice||null;let canGrade=!!q.answer;let options=['A','B','C','D'];box.innerHTML=`<article class="card"><div class="meta"><span class="pill">${q.year} 年</span><span class="pill">科目 A</span><span class="pill">第 ${q.number} 題</span><span class="pill">${q.topic}</span>${canGrade?'':'<span class="pill" style="background:#fff7e6;color:#9a5b00">待官方答案</span>'}</div><div class="qtext">${esc(q.text)}</div><div class="opts">${options.map(o=>`<button class="opt ${selected===o?'sel':''}" data-o="${o}">${o}</button>`).join('')}</div><div class="actions"><button class="btn primary" id="submit" ${!selected?'disabled':''}>${canGrade?'送出答案':'記錄作答'}</button><button class="btn warn" id="fav">${state.favorite[q.id]?'★ 已收藏':'☆ 收藏'}</button><a class="btn secondary" href="assets/${q.year}_A.pdf#page=${q.page}" target="_blank" style="text-decoration:none">📄 查看原始題本</a></div><div id="feedback"></div><div class="navrow"><button class="btn secondary" id="prev">← 上一題</button><div class="small">${idx+1} / ${list.length}</div><button class="btn secondary" id="next">下一題 →</button></div><div class="progressbar"><i style="width:${(idx+1)/list.length*100}%"></i></div></article>`;
 box.querySelectorAll('.opt').forEach(b=>b.onclick=()=>{selected=b.dataset.o;shown=false;render()});$('#submit').onclick=()=>submit(q);$('#fav').onclick=()=>{state.favorite[q.id]=!state.favorite[q.id];save();render();stats()};$('#prev').onclick=()=>{idx=(idx-1+list.length)%list.length;selected=null;shown=false;render()};$('#next').onclick=()=>{idx=(idx+1)%list.length;selected=null;shown=false;render()};if(old&&shown)feedback(q,old.choice);stats()}
function submit(q){if(!selected)return;state.answers[q.id]={choice:selected,ts:Date.now()};save();shown=true;feedback(q,selected);stats()}
function feedback(q,choice){let fb=$('#feedback');document.querySelectorAll('.opt').forEach(b=>{if(q.answer&&b.dataset.o===q.answer)b.classList.add('correct');if(q.answer&&b.dataset.o===choice&&choice!==q.answer)b.classList.add('wrong')});if(q.answer){let ok=choice===q.answer;fb.innerHTML=`<div class="explain"><b style="color:${ok?'#15803d':'#c62828'}">${ok?'✓ 答對了':'✗ 答錯了，正確答案是 '+q.answer}</b><br>${esc(q.explanation)}</div>`}else fb.innerHTML=`<div class="explain"><b>已記錄你的選擇：${choice}</b><br>${esc(q.explanation)}</div>`}
function renderPapers(){let h='';for(let y=108;y<=114;y++){h+=`<a class="paper" href="assets/${y}_A.pdf" target="_blank"><span><b>${y} 年 科目 A</b><br><span class="small">電路學、電子學</span></span><span>開啟 PDF ↗</span></a><a class="paper" href="assets/${y}_B.pdf" target="_blank"><span><b>${y} 年 科目 B</b><br><span class="small">電力系統、電機機械${y<=112&&y!==110?'／電磁學':''}</span></span><span>開啟 PDF ↗</span></a>`}$('#papers').innerHTML=h}
function esc(s){return String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))} init();
