const Q=window.QUESTION_BANK||[];
const LS='taipowerQuizV3';
let state=JSON.parse(localStorage.getItem(LS)||'{"answers":{},"favorite":{},"examHistory":[]}');
state.answers=state.answers||{}; state.favorite=state.favorite||{}; state.examHistory=state.examHistory||[];
let list=[],idx=0,selected=null,shown=false;
let exam={active:false,questions:[],answers:{},idx:0,startedAt:0,endsAt:0,timerId:null};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const save=()=>localStorage.setItem(LS,JSON.stringify(state));
const esc=s=>String(s??'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function groupOf(topic=''){if(/三相|功率/.test(topic))return 'threephase'; if(/運算放大器|OP/.test(topic))return 'opamp'; if(/電容|電感|暫態/.test(topic))return 'transient'; if(/BJT|MOSFET|二極體/.test(topic))return 'semiconductor'; if(/拉普拉斯/.test(topic))return 'laplace'; if(/戴維寧/.test(topic))return 'thevenin'; return 'basic';}
function formula(topic){const m={
 'threephase':'Y 接：V相=V線/√3、I線=I相；Δ 接：V線=V相、I線=√3I相；功率 P=√3V_LI_Lcosφ。',
 'opamp':'理想 OP Amp 負回授：i+=i−=0、V+=V−；用 KCL/KVL 找關係，再求 Vo。',
 'transient':'電容 i=C·dv/dt、電感 v=L·di/dt；一階響應 x(t)=x(∞)+[x(0+)-x(∞)]e^(−t/τ)。',
 'semiconductor':'先判斷導通區／飽和區／截止區，再套對應方程；BJT 常用 VBE≈0.7 V。',
 'laplace':'L{sin at}=a/(s²+a²)、L{cos at}=s/(s²+a²)，位移與線性性質要一起用。',
 'thevenin':'Vth=開路端電壓；Zth=獨立源關掉後由端點看入的等效阻抗。',
 'basic':'優先用歐姆定律、KCL、KVL，先化簡電路再代數值。'
}; return m[groupOf(topic)]}
function pitfall(topic){const m={
 'threephase':'線量與相量容易混用，也常忘記 √3 與相位 ±30°。',
 'opamp':'忘記先確認是否為負回授，或把虛短路誤用在不成立的情況。',
 'transient':'t=0⁻ 與 t=0⁺ 連續條件、時常數 Rth 常是失分點。',
 'semiconductor':'沒有先判斷元件工作區域，就直接代公式。',
 'laplace':'正弦、餘弦對應式寫反，或忽略位移項 e^{-as}。',
 'thevenin':'關閉獨立源時，電壓源短路、電流源開路，常常搞反。',
 'basic':'符號方向、單位換算、串並聯等效順序要先確認。'
}; return m[groupOf(topic)]}
function visualCaption(topic){const m={
 'threephase':'用小圖快速記住 Y/Δ、相量與三相功率關係。',
 'opamp':'以三角形 OP 模型整理輸入端、輸出端與回授概念。',
 'transient':'把暫態曲線與元件連續性放在一起看最容易理解。',
 'semiconductor':'先辨識元件，再判斷操作區與基本方程。',
 'laplace':'把時域訊號轉到 s 域，常用表格與位移觀念一起記。',
 'thevenin':'先化簡成等效源，再回來求負載端電壓或電流。',
 'basic':'先用基本電路定律，把整體關係寫清楚。'
}; return m[groupOf(topic)]}
function topicSvg(topic){switch(groupOf(topic)){
 case 'threephase': return `<svg viewBox="0 0 170 120" aria-hidden="true"><rect x="8" y="8" width="154" height="104" rx="14" fill="#f7fbfe" stroke="#d7ebf7"/><circle cx="42" cy="36" r="8" fill="#0ea5e9"/><circle cx="30" cy="58" r="8" fill="#38bdf8"/><circle cx="54" cy="58" r="8" fill="#075985"/><path d="M42 36v30M30 58h24" stroke="#075985" stroke-width="4" stroke-linecap="round"/><path d="M102 31l24 40H78z" fill="none" stroke="#0ea5e9" stroke-width="4"/><text x="18" y="90" font-size="11" fill="#0f172a">Y 接</text><text x="92" y="90" font-size="11" fill="#0f172a">Δ 接</text><text x="18" y="103" font-size="10" fill="#64748b">P=√3VLI Lcosφ</text></svg>`;
 case 'opamp': return `<svg viewBox="0 0 170 120" aria-hidden="true"><rect x="8" y="8" width="154" height="104" rx="14" fill="#f7fbfe" stroke="#d7ebf7"/><path d="M54 28l56 32-56 32z" fill="#e0f2fe" stroke="#075985" stroke-width="3"/><path d="M24 46h30M24 74h30M110 60h34" stroke="#075985" stroke-width="3" stroke-linecap="round"/><path d="M130 60V32H86" fill="none" stroke="#0ea5e9" stroke-width="3"/><text x="31" y="43" font-size="12" fill="#0f172a">+</text><text x="31" y="82" font-size="12" fill="#0f172a">−</text><text x="116" y="54" font-size="10" fill="#64748b">Vo</text></svg>`;
 case 'transient': return `<svg viewBox="0 0 170 120" aria-hidden="true"><rect x="8" y="8" width="154" height="104" rx="14" fill="#f7fbfe" stroke="#d7ebf7"/><path d="M26 90H148M34 98V24" stroke="#94a3b8" stroke-width="2"/><path d="M38 82c20 0 18-44 36-44 18 0 12 36 34 36 12 0 17-9 30-9" fill="none" stroke="#0ea5e9" stroke-width="4" stroke-linecap="round"/><text x="42" y="28" font-size="10" fill="#64748b">x(t)</text><text x="142" y="102" font-size="10" fill="#64748b">t</text><text x="47" y="108" font-size="10" fill="#0f172a">τ</text></svg>`;
 case 'semiconductor': return `<svg viewBox="0 0 170 120" aria-hidden="true"><rect x="8" y="8" width="154" height="104" rx="14" fill="#f7fbfe" stroke="#d7ebf7"/><path d="M44 24v72M44 60h28M72 40v40M72 40l24-10M72 80l24 10" stroke="#075985" stroke-width="3" stroke-linecap="round"/><path d="M104 49l18 0M104 71l18 0" stroke="#0ea5e9" stroke-width="3"/><text x="24" y="20" font-size="10" fill="#64748b">B</text><text x="95" y="40" font-size="10" fill="#64748b">C</text><text x="95" y="86" font-size="10" fill="#64748b">E</text><path d="M87 76l8 6-1-10" fill="#0ea5e9"/></svg>`;
 case 'laplace': return `<svg viewBox="0 0 170 120" aria-hidden="true"><rect x="8" y="8" width="154" height="104" rx="14" fill="#f7fbfe" stroke="#d7ebf7"/><path d="M26 84c10-32 20-52 34-52s12 28 22 28 10-18 18-18 10 13 20 13" fill="none" stroke="#0ea5e9" stroke-width="4" stroke-linecap="round"/><path d="M72 95h28" stroke="#075985" stroke-width="3"/><path d="M98 95l-8-6M98 95l-8 6" stroke="#075985" stroke-width="3"/><text x="18" y="103" font-size="10" fill="#64748b">time domain</text><text x="102" y="103" font-size="10" fill="#64748b">s-domain</text><text x="108" y="56" font-size="13" fill="#0f172a">F(s)</text></svg>`;
 case 'thevenin': return `<svg viewBox="0 0 170 120" aria-hidden="true"><rect x="8" y="8" width="154" height="104" rx="14" fill="#f7fbfe" stroke="#d7ebf7"/><circle cx="42" cy="60" r="16" fill="#e0f2fe" stroke="#075985" stroke-width="3"/><path d="M42 50v20M32 60h20" stroke="#075985" stroke-width="3"/><path d="M58 60h26M84 44v32M94 46l12 0M94 54l12 0M94 62l12 0M94 70l12 0" stroke="#0ea5e9" stroke-width="3" stroke-linecap="round"/><path d="M106 60h24" stroke="#075985" stroke-width="3"/><text x="20" y="90" font-size="10" fill="#64748b">Vth</text><text x="92" y="88" font-size="10" fill="#64748b">Rth</text></svg>`;
 default: return `<svg viewBox="0 0 170 120" aria-hidden="true"><rect x="8" y="8" width="154" height="104" rx="14" fill="#f7fbfe" stroke="#d7ebf7"/><path d="M26 40h22l8-10 12 20 12-20 12 20 8-10h22" fill="none" stroke="#0ea5e9" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/><path d="M26 80h22M108 80h36" stroke="#075985" stroke-width="4" stroke-linecap="round"/><circle cx="80" cy="80" r="14" fill="#e0f2fe" stroke="#075985" stroke-width="3"/><text x="74" y="85" font-size="12" fill="#0f172a">A</text></svg>`;
 }}
function detail(q){return `<div class="rich-solution"><div class="visual-wrap">${topicSvg(q.topic)}<div><h4>📷 圖解觀念</h4><p class="visual-caption">${esc(visualCaption(q.topic))}</p></div></div><div class="info-grid"><div class="info-box"><h4>① 解題核心</h4><p>${esc(q.explanation)}</p></div><div class="info-box"><h4>② 建議公式／方法</h4><p>${esc(formula(q.topic))}</p></div><div class="info-box"><h4>③ 作答檢查</h4><p>${esc(pitfall(q.topic))}</p></div></div></div>`}
function init(){
 [...new Set(Q.map(q=>q.year))].sort().forEach(y=>$('#year').add(new Option(y+' 年',y)));
 [...new Set(Q.map(q=>q.topic))].sort().forEach(t=>$('#topic').add(new Option(t,t)));
 ['year','topic','status'].forEach(id=>$('#'+id).onchange=filter); $('#search').oninput=filter;
 $('#random').onclick=()=>{if(list.length){idx=Math.floor(Math.random()*list.length);selected=null;shown=false;renderPractice()}};
 $('#reset').onclick=()=>{if(confirm('確定清除所有一般刷題紀錄、收藏與模擬考成績？')){state={answers:{},favorite:{},examHistory:[]};save();filter();renderAnalysis()}};
 $$('.tab').forEach(b=>b.onclick=()=>switchView(b.dataset.view));
 $('#startExam').onclick=startExam; $('#submitExam').onclick=()=>finishExam(false);
 renderTopicStrip(); filter(); renderAnalysis();
}
function renderTopicStrip(){
 const items=[
  ['🔌','電阻電路','KCL、KVL、串並聯與歐姆定律，是所有題型的基礎。'],
  ['📐','三相交流','Y/Δ、相量、功率因數與三相功率是常見大宗題型。'],
  ['📉','拉普拉斯／暫態','善用標準轉換表與一階響應公式，速度會快很多。'],
  ['🔬','半導體','BJT、MOSFET、二極體先判斷工作區，再代公式。']
 ];
 $('#topicStrip').innerHTML=items.map(([i,t,d])=>`<article class="card topic-card"><div class="topic-card-head"><div class="topic-icon">${i}</div><div><b>${t}</b></div></div><p>${d}</p></article>`).join('');
}
function switchView(v){$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$$('.view').forEach(x=>x.classList.remove('active'));$('#'+v+'View').classList.add('active');if(v==='analysis')renderAnalysis()}
function filter(){let y=$('#year').value,t=$('#topic').value,s=$('#status').value,k=$('#search').value.trim().toLowerCase();list=Q.filter(q=>(y==='all'||String(q.year)===y)&&(t==='all'||q.topic===t)&&(!k||q.text.toLowerCase().includes(k)||q.topic.toLowerCase().includes(k)));if(s!=='all')list=list.filter(q=>{let a=state.answers[q.id],f=state.favorite[q.id];if(s==='unanswered')return !a;if(s==='answered')return !!a;if(s==='wrong')return a&&q.answer&&a.choice!==q.answer;if(s==='favorite')return !!f});idx=0;selected=null;shown=false;renderPractice();stats()}
function stats(){let done=list.filter(q=>state.answers[q.id]).length, graded=list.filter(q=>state.answers[q.id]&&q.answer),ok=graded.filter(q=>state.answers[q.id].choice===q.answer).length;$('#sTotal').textContent=list.length;$('#sDone').textContent=done;$('#sRate').textContent=graded.length?Math.round(ok/graded.length*100)+'%':'—';$('#sFav').textContent=list.filter(q=>state.favorite[q.id]||(state.answers[q.id]&&q.answer&&state.answers[q.id].choice!==q.answer)).length}
function renderPractice(){let box=$('#quiz');if(!list.length){box.innerHTML='<div class="card empty">沒有符合目前篩選條件的題目。</div>';return}let q=list[idx],old=state.answers[q.id];selected=selected||old?.choice||null;let opts=['A','B','C','D'];box.innerHTML=`<article class="card"><div class="meta"><span class="pill">${q.year} 年</span><span class="pill">科目 A</span><span class="pill">第 ${q.number} 題</span><span class="pill">${esc(q.topic)}</span>${q.answer?'':'<span class="pill pending">待官方答案</span>'}</div><div class="qtext">${esc(q.text)}</div><div class="opts">${opts.map(o=>`<button class="opt ${selected===o?'sel':''}" data-o="${o}">${o}</button>`).join('')}</div><div class="actions"><button class="btn primary" id="submit" ${!selected?'disabled':''}>${q.answer?'送出答案':'記錄作答'}</button><button class="btn warn" id="fav">${state.favorite[q.id]?'★ 已收藏':'☆ 收藏'}</button><button class="btn secondary" id="sourceInfo">📄 原題說明</button></div><div id="feedback"></div><div class="navrow"><button class="btn secondary" id="prev">← 上一題</button><div class="small">${idx+1} / ${list.length}</div><button class="btn secondary" id="next">下一題 →</button></div><div class="progressbar"><i style="width:${(idx+1)/list.length*100}%"></i></div></article>`;
 box.querySelectorAll('.opt').forEach(b=>b.onclick=()=>{selected=b.dataset.o;shown=false;renderPractice()});$('#submit').onclick=()=>submitPractice(q);$('#fav').onclick=()=>{state.favorite[q.id]=!state.favorite[q.id];save();renderPractice();stats()};$('#prev').onclick=()=>{idx=(idx-1+list.length)%list.length;selected=null;shown=false;renderPractice()};$('#next').onclick=()=>{idx=(idx+1)%list.length;selected=null;shown=false;renderPractice()};$('#sourceInfo').onclick=()=>alert(`第 ${q.year} 年科目 A 第 ${q.number} 題。公開版未附原始 PDF；若本題含電路圖或示意圖，請搭配原始歷屆試題閱讀。`);if(old&&shown)feedback(q,old.choice);stats()}
function submitPractice(q){if(!selected)return;state.answers[q.id]={choice:selected,ts:Date.now()};save();shown=true;feedback(q,selected);stats()}
function feedback(q,choice){let fb=$('#feedback');$$('.opt').forEach(b=>{if(q.answer&&b.dataset.o===q.answer)b.classList.add('correct');if(q.answer&&b.dataset.o===choice&&choice!==q.answer)b.classList.add('wrong')});if(q.answer){let ok=choice===q.answer;fb.innerHTML=`<div class="explain"><b style="color:${ok?'var(--good)':'var(--bad)'}">${ok?'✓ 答對了':'✗ 答錯了，正確答案是 '+q.answer}</b>${detail(q)}</div>`}else fb.innerHTML=`<div class="explain"><b>已記錄你的選擇：${choice}</b><div class="solution">目前尚未匯入官方答案，因此不判定對錯。</div></div>`}
function startExam(){let pool=Q.filter(q=>q.answer);if(pool.length<50){alert('目前可判分題目不足 50 題。');return}exam={active:true,questions:shuffle(pool).slice(0,50),answers:{},idx:0,startedAt:Date.now(),endsAt:Date.now()+90*60*1000,timerId:null};$('#examSetup').classList.add('hidden');$('#examResult').classList.add('hidden');$('#examDesk').classList.remove('hidden');$('#timer').classList.remove('hidden');exam.timerId=setInterval(tick,1000);tick();renderExamQuestion()}
function tick(){let left=Math.max(0,exam.endsAt-Date.now()),sec=Math.ceil(left/1000),m=Math.floor(sec/60),s=sec%60;$('#timer').textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;$('#timer').classList.toggle('urgent',sec<=300);if(left<=0&&exam.active)finishExam(true)}
function renderExamQuestion(){let q=exam.questions[exam.idx],choice=exam.answers[q.id]||null;$('#examQuestion').innerHTML=`<article class="card"><div class="exam-status"><b>第 ${exam.idx+1} / 50 題</b><span>已作答 ${Object.keys(exam.answers).length} 題</span></div><div class="meta"><span class="pill">${q.year} 年</span><span class="pill">${esc(q.topic)}</span></div><div class="qtext">${esc(q.text)}</div><div class="opts">${['A','B','C','D'].map(o=>`<button class="opt ${choice===o?'sel':''}" data-o="${o}">${o}</button>`).join('')}</div><div class="navrow"><button class="btn secondary" id="ePrev">← 上一題</button><button class="btn primary" id="eNext">下一題 →</button></div></article>`;$$('#examQuestion .opt').forEach(b=>b.onclick=()=>{exam.answers[q.id]=b.dataset.o;renderExamQuestion()});$('#ePrev').onclick=()=>{exam.idx=Math.max(0,exam.idx-1);renderExamQuestion()};$('#eNext').onclick=()=>{exam.idx=Math.min(49,exam.idx+1);renderExamQuestion()};renderNav()}
function renderNav(){$('#navGrid').innerHTML=exam.questions.map((q,i)=>`<button class="qjump ${exam.answers[q.id]?'done':''} ${i===exam.idx?'now':''}" data-i="${i}">${i+1}</button>`).join('');$$('.qjump').forEach(b=>b.onclick=()=>{exam.idx=+b.dataset.i;renderExamQuestion()})}
function finishExam(auto){if(!auto&&!confirm(`目前已作答 ${Object.keys(exam.answers).length}/50 題，確定交卷？`))return;exam.active=false;clearInterval(exam.timerId);$('#timer').classList.add('hidden');let correct=0,topics={};exam.questions.forEach(q=>{let c=exam.answers[q.id]||null,ok=c===q.answer;if(ok)correct++;if(!topics[q.topic])topics[q.topic]={correct:0,total:0};topics[q.topic].total++;if(ok)topics[q.topic].correct++});let score=correct*2,rec={ts:Date.now(),score,correct,total:50,duration:Math.min(90*60*1000,Date.now()-exam.startedAt),topics};state.examHistory.push(rec);save();$('#examDesk').classList.add('hidden');let wrongs=exam.questions.filter(q=>(exam.answers[q.id]||null)!==q.answer);$('#examResult').innerHTML=`<div class="card score-hero"><div>${auto?'時間到，自動交卷':'模擬考完成'}</div><strong>${score}</strong><div>答對 ${correct}/50 題｜答錯或未答 ${50-correct} 題</div><button class="btn primary" id="newExam">再考一次</button></div><article class="card"><h2>逐題檢討</h2>${wrongs.length?wrongs.map(q=>`<div class="review-item"><b>${q.year} 年第 ${q.number} 題｜${esc(q.topic)}</b><div>你的答案：${exam.answers[q.id]||'未作答'}　正確答案：<b>${q.answer}</b></div>${detail(q)}</div>`).join(''):'<div class="empty">全對！沒有錯題。</div>'}</article>`;$('#examResult').classList.remove('hidden');$('#newExam').onclick=()=>{$('#examResult').classList.add('hidden');$('#examSetup').classList.remove('hidden')};renderAnalysis()}
function renderAnalysis(){let H=state.examHistory||[];drawChart(H);let agg={};H.forEach(r=>Object.entries(r.topics||{}).forEach(([t,v])=>{if(!agg[t])agg[t]={correct:0,total:0};agg[t].correct+=v.correct;agg[t].total+=v.total}));let rows=Object.entries(agg).map(([t,v])=>({t,...v,rate:v.total?v.correct/v.total:0})).sort((a,b)=>a.rate-b.rate);$('#weakness').innerHTML=rows.length?rows.slice(0,12).map(x=>`<div class="weak-row"><div class="weak-top"><b>${esc(x.t)}</b><span>${Math.round(x.rate*100)}%（${x.correct}/${x.total}）</span></div><div class="bar"><i style="width:${x.rate*100}%"></i></div></div>`).join(''):'<div class="empty">完成至少一次模擬考後，這裡會依章節顯示正確率。</div>';$('#history').innerHTML=H.length?`<table class="history-table"><thead><tr><th>日期</th><th>分數</th><th>答對</th><th>用時</th></tr></thead><tbody>${[...H].reverse().map(r=>`<tr><td>${new Date(r.ts).toLocaleString('zh-TW')}</td><td><b>${r.score}</b></td><td>${r.correct}/50</td><td>${Math.round(r.duration/60000)} 分</td></tr>`).join('')}</tbody></table>`:'<div class="empty">尚無模擬考紀錄。</div>'}
function drawChart(H){let c=$('#scoreChart'),ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height);if(!H.length){c.classList.add('hidden');$('#scoreEmpty').classList.remove('hidden');return}c.classList.remove('hidden');$('#scoreEmpty').classList.add('hidden');let data=H.slice(-10),pad=42,w=c.width-pad*2,h=c.height-pad*2;ctx.strokeStyle='#cbd5e1';ctx.lineWidth=1;for(let y=0;y<=100;y+=20){let py=pad+h-(y/100*h);ctx.beginPath();ctx.moveTo(pad,py);ctx.lineTo(pad+w,py);ctx.stroke();ctx.fillStyle='#64748b';ctx.fillText(y,8,py+4)}ctx.strokeStyle='#075985';ctx.lineWidth=3;ctx.beginPath();data.forEach((r,i)=>{let x=pad+(data.length===1?w/2:i*w/(data.length-1)),y=pad+h-r.score/100*h;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();data.forEach((r,i)=>{let x=pad+(data.length===1?w/2:i*w/(data.length-1)),y=pad+h-r.score/100*h;ctx.fillStyle='#0ea5e9';ctx.beginPath();ctx.arc(x,y,5,0,Math.PI*2);ctx.fill();ctx.fillStyle='#0f172a';ctx.fillText(r.score,x-7,y-10)})}
init();
