const Q=window.QUESTION_BANK||[];
const LS='taipowerQuizV2';
let state=JSON.parse(localStorage.getItem(LS)||'{"answers":{},"favorite":{},"examHistory":[]}');
state.answers=state.answers||{}; state.favorite=state.favorite||{}; state.examHistory=state.examHistory||[];
let list=[],idx=0,selected=null,shown=false;
let exam={active:false,questions:[],answers:{},idx:0,startedAt:0,endsAt:0,timerId:null};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const save=()=>localStorage.setItem(LS,JSON.stringify(state));
const esc=s=>String(s??'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function formula(topic){const m={
 '三相交流':'三相常用：Y 接 V相=V線/√3、I線=I相；Δ 接 V線=V相、I線=√3 I相，並注意 ±30° 相位。',
 '戴維寧等效':'戴維寧：Vth=開路端電壓；Zth=關閉獨立源後由端點看入之等效阻抗。',
 '運算放大器':'理想 OP Amp 負回授：i+=i−=0、V+=V−，再以 KCL 解節點。',
 '電容/暫態':'電容 i=C·dv/dt，電容電壓不可瞬變；一階響應 x(t)=x(∞)+[x(0+)-x(∞)]e^(−t/τ)。',
 '電感/暫態':'電感 v=L·di/dt，電感電流不可瞬變；RL 時常數 τ=L/Rth。',
 '功率因數':'P=S cosφ、Q=S sinφ、Q=P tanφ；補償電容提供超前無功。',
 '拉普拉斯':'L{sin at}=a/(s²+a²)，L{cos at}=s/(s²+a²)，搭配線性與位移性質。',
 'BJT':'主動區常用 Ic≈βIb、Ie=Ic+Ib；矽 BJT 可先以 VBE≈0.7 V 判斷偏壓。',
 'MOSFET':'先判斷截止／三極／飽和區，再選對應 I_D 方程；小訊號常用 gm。',
 '二極體':'先判斷導通/截止；矽二極體定壓降模型常取約 0.7 V。',
 '電阻電路':'優先用歐姆定律 V=IR、KCL、KVL 與串並聯等效化簡。'
}; return m[topic]||'先辨識題型與已知條件，列出控制方程，再代入數值並檢查單位、相位與答案量級。'}
function pitfall(topic){if(/三相|功率/.test(topic))return '常見失分：線量與相量混用、忽略 √3 或相位方向。';if(/暫態|電容|電感/.test(topic))return '常見失分：忘記 t=0⁻ 與 t=0⁺ 的連續條件，或時常數取錯等效電阻。';if(/BJT|MOSFET|二極體/.test(topic))return '常見失分：未先確認元件操作區域，就直接套用公式。';return '常見失分：太早代數字、符號方向未先定義，或忽略題目單位。'}
function detail(q){return `<div class="solution"><h4>① 解題核心</h4><div>${esc(q.explanation)}</div><h4>② 建議公式／方法</h4><div>${esc(formula(q.topic))}</div><h4>③ 作答檢查</h4><div>${esc(pitfall(q.topic))}</div></div>`}
function init(){
 [...new Set(Q.map(q=>q.year))].sort().forEach(y=>$('#year').add(new Option(y+' 年',y)));
 [...new Set(Q.map(q=>q.topic))].sort().forEach(t=>$('#topic').add(new Option(t,t)));
 ['year','topic','status'].forEach(id=>$('#'+id).onchange=filter); $('#search').oninput=filter;
 $('#random').onclick=()=>{if(list.length){idx=Math.floor(Math.random()*list.length);selected=null;shown=false;renderPractice()}};
 $('#reset').onclick=()=>{if(confirm('確定清除所有一般刷題紀錄、收藏與模擬考成績？')){state={answers:{},favorite:{},examHistory:[]};save();filter();renderAnalysis()}};
 $$('.tab').forEach(b=>b.onclick=()=>switchView(b.dataset.view));
 $('#startExam').onclick=startExam; $('#submitExam').onclick=()=>finishExam(false);
 filter(); renderAnalysis();
}
function switchView(v){$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$$('.view').forEach(x=>x.classList.remove('active'));$('#'+v+'View').classList.add('active');if(v==='analysis')renderAnalysis()}
function filter(){let y=$('#year').value,t=$('#topic').value,s=$('#status').value,k=$('#search').value.trim().toLowerCase();list=Q.filter(q=>(y==='all'||String(q.year)===y)&&(t==='all'||q.topic===t)&&(!k||q.text.toLowerCase().includes(k)||q.topic.toLowerCase().includes(k)));if(s!=='all')list=list.filter(q=>{let a=state.answers[q.id],f=state.favorite[q.id];if(s==='unanswered')return !a;if(s==='answered')return !!a;if(s==='wrong')return a&&q.answer&&a.choice!==q.answer;if(s==='favorite')return !!f});idx=0;selected=null;shown=false;renderPractice();stats()}
function stats(){let done=list.filter(q=>state.answers[q.id]).length, graded=list.filter(q=>state.answers[q.id]&&q.answer),ok=graded.filter(q=>state.answers[q.id].choice===q.answer).length;$('#sTotal').textContent=list.length;$('#sDone').textContent=done;$('#sRate').textContent=graded.length?Math.round(ok/graded.length*100)+'%':'—';$('#sFav').textContent=list.filter(q=>state.favorite[q.id]||(state.answers[q.id]&&q.answer&&state.answers[q.id].choice!==q.answer)).length}
function renderPractice(){let box=$('#quiz');if(!list.length){box.innerHTML='<div class="card empty">沒有符合目前篩選條件的題目。</div>';return}let q=list[idx],old=state.answers[q.id];selected=selected||old?.choice||null;let opts=['A','B','C','D'];box.innerHTML=`<article class="card"><div class="meta"><span class="pill">${q.year} 年</span><span class="pill">科目 A</span><span class="pill">第 ${q.number} 題</span><span class="pill">${esc(q.topic)}</span>${q.answer?'':'<span class="pill pending">待官方答案</span>'}</div><div class="qtext">${esc(q.text)}</div><div class="opts">${opts.map(o=>`<button class="opt ${selected===o?'sel':''}" data-o="${o}">${o}</button>`).join('')}</div><div class="actions"><button class="btn primary" id="submit" ${!selected?'disabled':''}>${q.answer?'送出答案':'記錄作答'}</button><button class="btn warn" id="fav">${state.favorite[q.id]?'★ 已收藏':'☆ 收藏'}</button><button class="btn secondary" id="sourceInfo">📄 原題說明</button></div><div id="feedback"></div><div class="navrow"><button class="btn secondary" id="prev">← 上一題</button><div class="small">${idx+1} / ${list.length}</div><button class="btn secondary" id="next">下一題 →</button></div><div class="progressbar"><i style="width:${(idx+1)/list.length*100}%"></i></div></article>`;
 box.querySelectorAll('.opt').forEach(b=>b.onclick=()=>{selected=b.dataset.o;shown=false;renderPractice()});$('#submit').onclick=()=>submitPractice(q);$('#fav').onclick=()=>{state.favorite[q.id]=!state.favorite[q.id];save();renderPractice();stats()};$('#prev').onclick=()=>{idx=(idx-1+list.length)%list.length;selected=null;shown=false;renderPractice()};$('#next').onclick=()=>{idx=(idx+1)%list.length;selected=null;shown=false;renderPractice()};$('#sourceInfo').onclick=()=>alert(`第 ${q.year} 年科目 A 第 ${q.number} 題。公開版未附原始 PDF；若本題含電路圖或示意圖，請搭配原始歷屆試題閱讀。`);if(old&&shown)feedback(q,old.choice);stats()}
function submitPractice(q){if(!selected)return;state.answers[q.id]={choice:selected,ts:Date.now()};save();shown=true;feedback(q,selected);stats()}
function feedback(q,choice){let fb=$('#feedback');$$('.opt').forEach(b=>{if(q.answer&&b.dataset.o===q.answer)b.classList.add('correct');if(q.answer&&b.dataset.o===choice&&choice!==q.answer)b.classList.add('wrong')});if(q.answer){let ok=choice===q.answer;fb.innerHTML=`<div class="explain"><b style="color:${ok?'var(--good)':'var(--bad)'}">${ok?'✓ 答對了':'✗ 答錯了，正確答案是 '+q.answer}</b>${detail(q)}</div>`}else fb.innerHTML=`<div class="explain"><b>已記錄你的選擇：${choice}</b><div class="solution">目前尚未匯入官方答案，因此不判定對錯。</div></div>`}
function startExam(){let pool=Q.filter(q=>q.answer);if(pool.length<50){alert('目前可判分題目不足 50 題。');return}exam={active:true,questions:shuffle(pool).slice(0,50),answers:{},idx:0,startedAt:Date.now(),endsAt:Date.now()+90*60*1000,timerId:null};$('#examSetup').classList.add('hidden');$('#examResult').classList.add('hidden');$('#examDesk').classList.remove('hidden');$('#timer').classList.remove('hidden');exam.timerId=setInterval(tick,1000);tick();renderExamQuestion()}
function tick(){let left=Math.max(0,exam.endsAt-Date.now()),sec=Math.ceil(left/1000),m=Math.floor(sec/60),s=sec%60;$('#timer').textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;$('#timer').classList.toggle('urgent',sec<=300);if(left<=0&&exam.active)finishExam(true)}
function renderExamQuestion(){let q=exam.questions[exam.idx],choice=exam.answers[q.id]||null;$('#examQuestion').innerHTML=`<article class="card"><div class="exam-status"><b>第 ${exam.idx+1} / 50 題</b><span>已作答 ${Object.keys(exam.answers).length} 題</span></div><div class="meta"><span class="pill">${q.year} 年</span><span class="pill">${esc(q.topic)}</span></div><div class="qtext">${esc(q.text)}</div><div class="opts">${['A','B','C','D'].map(o=>`<button class="opt ${choice===o?'sel':''}" data-o="${o}">${o}</button>`).join('')}</div><div class="navrow"><button class="btn secondary" id="ePrev">← 上一題</button><button class="btn primary" id="eNext">下一題 →</button></div></article>`;$$('#examQuestion .opt').forEach(b=>b.onclick=()=>{exam.answers[q.id]=b.dataset.o;renderExamQuestion()});$('#ePrev').onclick=()=>{exam.idx=Math.max(0,exam.idx-1);renderExamQuestion()};$('#eNext').onclick=()=>{exam.idx=Math.min(49,exam.idx+1);renderExamQuestion()};renderNav()}
function renderNav(){$('#navGrid').innerHTML=exam.questions.map((q,i)=>`<button class="qjump ${exam.answers[q.id]?'done':''} ${i===exam.idx?'now':''}" data-i="${i}">${i+1}</button>`).join('');$$('.qjump').forEach(b=>b.onclick=()=>{exam.idx=+b.dataset.i;renderExamQuestion()})}
function finishExam(auto){if(!auto&&!confirm(`目前已作答 ${Object.keys(exam.answers).length}/50 題，確定交卷？`))return;exam.active=false;clearInterval(exam.timerId);$('#timer').classList.add('hidden');let correct=0,topics={};exam.questions.forEach(q=>{let c=exam.answers[q.id]||null,ok=c===q.answer;if(ok)correct++;if(!topics[q.topic])topics[q.topic]={correct:0,total:0};topics[q.topic].total++;if(ok)topics[q.topic].correct++});let score=correct*2,rec={ts:Date.now(),score,correct,total:50,duration:Math.min(90*60*1000,Date.now()-exam.startedAt),topics};state.examHistory.push(rec);save();$('#examDesk').classList.add('hidden');let wrongs=exam.questions.filter(q=>(exam.answers[q.id]||null)!==q.answer);$('#examResult').innerHTML=`<div class="card score-hero"><div>${auto?'時間到，自動交卷':'模擬考完成'}</div><strong>${score}</strong><div>答對 ${correct}/50 題｜答錯或未答 ${50-correct} 題</div><button class="btn primary" id="newExam">再考一次</button></div><article class="card"><h2>逐題檢討</h2>${wrongs.length?wrongs.map(q=>`<div class="review-item"><b>${q.year} 年第 ${q.number} 題｜${esc(q.topic)}</b><div>你的答案：${exam.answers[q.id]||'未作答'}　正確答案：<b>${q.answer}</b></div>${detail(q)}</div>`).join(''):'<div class="empty">全對！沒有錯題。</div>'}</article>`;$('#examResult').classList.remove('hidden');$('#newExam').onclick=()=>{$('#examResult').classList.add('hidden');$('#examSetup').classList.remove('hidden')};renderAnalysis()}
function renderAnalysis(){let H=state.examHistory||[];drawChart(H);let agg={};H.forEach(r=>Object.entries(r.topics||{}).forEach(([t,v])=>{if(!agg[t])agg[t]={correct:0,total:0};agg[t].correct+=v.correct;agg[t].total+=v.total}));let rows=Object.entries(agg).map(([t,v])=>({t,...v,rate:v.total?v.correct/v.total:0})).sort((a,b)=>a.rate-b.rate);$('#weakness').innerHTML=rows.length?rows.slice(0,12).map(x=>`<div class="weak-row"><div class="weak-top"><b>${esc(x.t)}</b><span>${Math.round(x.rate*100)}%（${x.correct}/${x.total}）</span></div><div class="bar"><i style="width:${x.rate*100}%"></i></div></div>`).join(''):'<div class="empty">完成至少一次模擬考後，這裡會依章節顯示正確率。</div>';$('#history').innerHTML=H.length?`<table class="history-table"><thead><tr><th>日期</th><th>分數</th><th>答對</th><th>用時</th></tr></thead><tbody>${[...H].reverse().map(r=>`<tr><td>${new Date(r.ts).toLocaleString('zh-TW')}</td><td><b>${r.score}</b></td><td>${r.correct}/50</td><td>${Math.round(r.duration/60000)} 分</td></tr>`).join('')}</tbody></table>`:'<div class="empty">尚無模擬考紀錄。</div>'}
function drawChart(H){let c=$('#scoreChart'),ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height);if(!H.length){c.classList.add('hidden');$('#scoreEmpty').classList.remove('hidden');return}c.classList.remove('hidden');$('#scoreEmpty').classList.add('hidden');let data=H.slice(-10),pad=42,w=c.width-pad*2,h=c.height-pad*2;ctx.strokeStyle='#cbd5e1';ctx.lineWidth=1;for(let y=0;y<=100;y+=20){let py=pad+h-(y/100*h);ctx.beginPath();ctx.moveTo(pad,py);ctx.lineTo(pad+w,py);ctx.stroke();ctx.fillStyle='#64748b';ctx.fillText(y,8,py+4)}ctx.strokeStyle='#075985';ctx.lineWidth=3;ctx.beginPath();data.forEach((r,i)=>{let x=pad+(data.length===1?w/2:i*w/(data.length-1)),y=pad+h-r.score/100*h;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();data.forEach((r,i)=>{let x=pad+(data.length===1?w/2:i*w/(data.length-1)),y=pad+h-r.score/100*h;ctx.fillStyle='#0ea5e9';ctx.beginPath();ctx.arc(x,y,5,0,Math.PI*2);ctx.fill();ctx.fillStyle='#0f172a';ctx.fillText(r.score,x-7,y-10)})}
init();
